# Generated by Django 3.1.2 on 2020-10-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='minutes_spent',
        ),
    ]
