# Generated by Django 3.1.2 on 2020-10-02 10:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField(verbose_name='')),
            ],
        ),
    ]
